/**
 * Codex profile. Codex brings far more than Claude's tool list: a shell,
 * unified exec, browser and computer use, plugins, apps, subagents, skills
 * from the user's home, hooks, memories… Session options alone cannot
 * switch these off, so the profile isolates Codex instead:
 *
 *   - its own CODEX_HOME (`~/.leuria/codex`) holding only the sign-in
 *     (done with ACP `authenticate`, like any agent) and
 *     a generated `config.toml`: read-only sandbox, no web search,
 *     approvals off, and EVERY feature flag of the pinned version turned
 *     off except the code-mode host that routes MCP tool calls;
 *   - a per-session HOME pointing at the empty sandbox, so nothing from
 *     the user's home (skills, AGENTS.md, configs) is discovered;
 *   - the page tools as the only MCP server, declared per session through
 *     `CODEX_CONFIG` with tool approval pre-granted (Codex's own approval
 *     prompt cannot reach the visitor through ACP).
 *
 * Checked against codex-acp 1.13.1 / codex 0.156.1 by `leuria test`: the
 * agent answers through page tools and cannot list or read the home folder.
 * The feature list is read from the installed Codex, so a new registry
 * version starts with everything off too.
 */

import { execFile } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { promisify } from "node:util";

import type { InstalledAgent } from "./agents.js";
import { homePath } from "./home.js";
import { WEBMCP_SERVER_NAME } from "./policy.js";
import type { AgentProfile } from "./profiles.js";

const execFileAsync = promisify(execFile);

/** Features Leuria needs; everything else is off. */
const ENABLED_FEATURES = new Set(["code_mode_host"]);

export function codexHome(): string {
	return homePath("codex");
}

/** Generate `config.toml` for the installed Codex. Idempotent per version. */
async function prepareCodexHome(agent: InstalledAgent): Promise<void> {
	const home = codexHome();
	mkdirSync(home, { recursive: true, mode: 0o700 });
	const launcher = join(agent.dir, "node_modules", "@openai", "codex", "bin", "codex.js");
	const stamp = join(home, ".leuria-config-for");
	if (existsSync(stamp) && readFileSync(stamp, "utf-8") === agent.version && existsSync(join(home, "config.toml"))) return;

	const { stdout } = await execFileAsync(process.execPath, [launcher, "features", "list"], {
		env: { ...process.env, CODEX_HOME: home, BUN_BE_BUN: "1" },
		timeout: 60_000,
	});
	const features = stdout
		.split("\n")
		.map((line) => line.trim().split(/\s+/)[0] ?? "")
		// Dotted names are children of a parent flag; the parent covers them.
		.filter((name) => /^[a-z0-9_]+$/.test(name));
	if (features.length < 10) throw new Error("Could not read Codex's feature list");

	const lines = [
		"# Generated by Leuria for its locked-down Codex. Do not edit: it is rewritten on upgrade.",
		'sandbox_mode = "read-only"',
		'approval_policy = "never"',
		'web_search = "disabled"',
		"",
		"[features]",
		...features.map((name) => `${name} = ${ENABLED_FEATURES.has(name)}`),
		"",
	];
	writeFileSync(join(home, "config.toml"), lines.join("\n"), { mode: 0o600 });
	writeFileSync(stamp, agent.version);
}

export const codexProfile: AgentProfile = {
	home: codexHome,
	prepare: prepareCodexHome,
	configure: (setup) => ({
		env: {
			// Leuria's own Codex home: its sign-in (through ACP authenticate) lands here.
			CODEX_HOME: codexHome(),
			HOME: setup.sandbox,
			USERPROFILE: setup.sandbox,
			INITIAL_AGENT_MODE: "read-only",
			CODEX_CONFIG: JSON.stringify({
				mcp_servers: {
					[WEBMCP_SERVER_NAME]: {
						url: setup.mcpUrl,
						http_headers: { Authorization: `Bearer ${setup.mcpToken}` },
						default_tools_approval_mode: "approve",
					},
				},
				...(setup.systemPrompt ? { developer_instructions: setup.systemPrompt } : {}),
			}),
		},
		// Declared through CODEX_CONFIG above, with approval; not through ACP.
		mcpServers: [],
		meta: {},
	}),
};
