#!/usr/bin/env node
// Writes the generated sources of the Connect UI:
// - src/tokens.ts: Leuria Pearl's tokens (packages/pearl/src/tokens.css) on
//   `:host`, so they live inside each element's shadow root. Light by
//   default, dark with the system or `appearance="dark"`.
// - fonts/: Plus Jakarta Sans (latin, latin-ext), loaded by the elements.
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = (path) => fileURLToPath(new URL(path, import.meta.url));

const selectors = new Map([
	[':root, [data-theme="light"] {', ":host {"],
	['[data-theme="dark"] {', ':host([appearance="dark"]) {'],
	[':root:not([data-theme="light"]) {', ':host(:not([appearance="light"])) {'],
	[":root {", ":host {"],
]);

const out = [];
for (const line of readFileSync(here("../../pearl/src/tokens.css"), "utf8").split("\n")) {
	const trimmed = line.trim();
	if (trimmed.startsWith("/*")) continue;
	// Type role classes (.display, .body…) are not used by the elements.
	if (/^\.[a-z0-9-]+ \{/.test(trimmed)) continue;
	const scoped = selectors.get(trimmed);
	if (!scoped && /\{$/.test(trimmed) && !trimmed.startsWith("@media")) throw new Error(`Unexpected selector in tokens.css: ${trimmed}`);
	out.push(scoped ? line.replace(trimmed, scoped) : line);
}
writeFileSync(
	here("../src/tokens.ts"),
	`// Generated by scripts/prepare.mjs from Leuria Pearl's tokens: do not edit.\nexport const tokens = \`\n${out.join("\n").trim()}\n\`;\n`,
);

const require = createRequire(import.meta.url);
const fontDir = join(dirname(require.resolve("@fontsource-variable/plus-jakarta-sans/package.json")));
mkdirSync(here("../fonts"), { recursive: true });
for (const file of ["plus-jakarta-sans-latin-wght-normal.woff2", "plus-jakarta-sans-latin-ext-wght-normal.woff2"]) {
	copyFileSync(join(fontDir, "files", file), join(here("../fonts"), file));
}
copyFileSync(join(fontDir, "LICENSE"), here("../fonts/LICENSE"));
console.log("Wrote src/tokens.ts and fonts/");
